### ISSUE TITLE
Memory problem when building flow with big number of parallel queries and optimize flag

### ISSUE THREAD

**Issue by starstuck** [dalmatinerdb/dflow#3]
We run into an issue with memory consumption of dalmatiner-frontend when running queries spanning across a lot of series. We were running 2 queries across 11k distinct series. When running
`dflow:build` on so big query parts with 'optimize' option erlang vm becomes growing in terms of memory consumption. That query with 11k series was enough to take all 32G of available memory, which forces OS to kill dalmatiner-frontend process.

The same query, without optimize flag runs fine on the same hardware and vm seems to be taking around 800MB to process it.

**Comment by Licenser** [comment]
this should be resolved.
